Repository linhpq0610/CoffeeShop, pull requests merged in 2023-11, with the labels that each got.

#17 refactor: update statisticProducts method
  app/controllers/admin/Statistic.php
  app/models/ProductModel.php
  app/views/admin/statistics/product.php
  app/views/admin/statistics/productChart.php
  app/views/client/components/relatedProducts.php
Labels: refactor

#19 refactor: update sign in feature
  app/controllers/client/Account.php
  app/controllers/client/Product.php
  configs/constants/index.php
  core/Controller.php
  index.php
Labels: refactor

#22 feat: add auto sign in feature
  CoffeeShop.sql
  app/controllers/client/Account.php
  app/models/UserTokenModel.php
  configs/constants/routes/client/account.php
  configs/routes/client/account.php
  core/Controller.php
Labels: feature

#45 refactor: update auto sign in feature
  .gitignore
  CoffeeShop.sql
  app/controllers/client/Account.php
  app/controllers/client/Product.php
  configs/constants/directories.php
  configs/constants/index.php
  configs/index.php
  configs/libraries.php
  configs/routes/client/account.php
  core/Controller.php
Labels: refactor

#46 17-11-2023, Version 2.2.5
  .gitignore
  CoffeeShop.sql
  app/controllers/client/Account.php
  app/controllers/client/Product.php
  configs/constants/directories.php
  configs/constants/index.php
  configs/index.php
  configs/libraries.php
  configs/routes/client/account.php
  core/Controller.php
Labels: release

#51 18-11-2023, Version 2.4.5
  app/controllers/admin/Product.php
  app/controllers/admin/User.php
  configs/routes/admin/product.php
  configs/routes/admin/users.php
Labels: release

#53 refactor: cải thiện chức năng hiển thị với tính năng xóa mềm
  app/controllers/admin/Category.php
  app/controllers/admin/Product.php
  app/controllers/admin/Statistic.php
  app/controllers/admin/User.php
  app/controllers/client/Account.php
  app/controllers/client/Product.php
  app/models/CategoryModel.php
  app/models/ProductModel.php
Labels: refactor

#59 feat: add restore and hard delete product
  app/controllers/admin/Product.php
  app/views/admin/components/restoreModal.php
  app/views/admin/products/productsDeleted.php
  configs/constants/routes/admin/product.php
  configs/routes/admin/product.php
Labels: feature

#58 feat: add restore and hard delete user
  app/controllers/admin/User.php
  app/views/admin/components/restoreModal.php
  app/views/admin/users/usersDeleted.php
  configs/constants/routes/admin/users.php
  configs/routes/admin/users.php
Labels: feature

#60 refactor: update Account controller
  app/controllers/client/Account.php
  app/views/client/account/account.php
  app/views/client/account/changePassword.php
  app/views/client/account/forgotPassword.php
  configs/routes/client/account.php
Labels: refactor

#61 21-11-2023. Version 2.8.7
  app/controllers/admin/Category.php
  app/controllers/admin/Product.php
  app/controllers/admin/Statistic.php
  app/controllers/admin/User.php
  app/controllers/client/Account.php
  app/controllers/client/Product.php
  app/models/CategoryModel.php
  app/models/CommentModel.php
  app/models/ProductModel.php
  app/models/UserTokenModel.php
  app/views/admin/components/menu.php
  app/views/admin/components/restoreModal.php
  app/views/admin/products/productsDeleted.php
  app/views/admin/statistics/comment.php
  app/views/admin/users/list.php
  app/views/admin/users/usersDeleted.php
  app/views/client/account/account.php
  app/views/client/account/changePassword.php
  app/views/client/account/forgotPassword.php
  configs/constants/routes/admin/product.php
  configs/constants/routes/admin/users.php
  configs/routes/admin/product.php
  configs/routes/admin/users.php
  configs/routes/client/account.php
  features/handleCheckboxes.js
  features/handleSingleRestore.js
Labels: release

#63 feat: add soft hard delete and restore category
  CoffeeShop.sql
  app/controllers/admin/Category.php
  app/views/admin/categories/categoriesDeleted.php
  app/views/admin/components/menu.php
  configs/constants/routes/admin/category.php
  configs/routes/admin/category.php
Labels: feature

#64 22-11-2023, Version 2.11.7
  .gitignore
  CoffeeShop.sql
  app/controllers/admin/Category.php
  app/views/admin/categories/categoriesDeleted.php
  app/views/admin/components/menu.php
  configs/constants/routes/admin/category.php
  configs/routes/admin/category.php
  public/libs/php-jwt/.gitattributes
  public/libs/php-jwt/.gitignore
  public/libs/php-jwt/.php-cs-fixer.dist.php
  public/libs/php-jwt/CHANGELOG.md
  public/libs/php-jwt/LICENSE
  public/libs/php-jwt/README.md
  public/libs/php-jwt/composer.json
  public/libs/php-jwt/phpstan.neon.dist
  public/libs/php-jwt/phpunit.xml.dist
  public/libs/php-jwt/src/BeforeValidException.php
  public/libs/php-jwt/src/CachedKeySet.php
  public/libs/php-jwt/src/ExpiredException.php
  public/libs/php-jwt/src/JWK.php
  public/libs/php-jwt/src/JWT.php
  public/libs/php-jwt/src/JWTExceptionWithPayloadInterface.php
  public/libs/php-jwt/src/Key.php
  public/libs/php-jwt/src/SignatureInvalidException.php
  public/libs/php-jwt/tests/CachedKeySetTest.php
  public/libs/php-jwt/tests/JWKTest.php
  public/libs/php-jwt/tests/JWTTest.php
  public/libs/php-jwt/tests/data/ec-jwkset.json
  public/libs/php-jwt/tests/data/ecdsa-private.pem
  public/libs/php-jwt/tests/data/ecdsa-public.pem
  public/libs/php-jwt/tests/data/ecdsa256-private.pem
  public/libs/php-jwt/tests/data/ecdsa384-private.pem
  public/libs/php-jwt/tests/data/ecdsa384-public.pem
  public/libs/php-jwt/tests/data/ed25519-1.pub
  public/libs/php-jwt/tests/data/ed25519-1.sec
  public/libs/php-jwt/tests/data/ed25519-jwkset.json
  public/libs/php-jwt/tests/data/rsa-jwkset.json
  public/libs/php-jwt/tests/data/rsa-with-passphrase.pem
  public/libs/php-jwt/tests/data/rsa1-private.pem
  public/libs/php-jwt/tests/data/rsa1-public.pub
  public/libs/php-jwt/tests/data/rsa2-private.pem
  public/libs/php-jwt/tests/data/secp256k1-private.pem
  public/libs/php-jwt/tests/data/secp256k1-public.pem
Labels: release

#65 fix: error single delete
  app/views/admin/categories/categoriesDeleted.php
  app/views/admin/products/productsDeleted.php
  app/views/admin/users/usersDeleted.php
Labels: fix

#69 fix: error show category
  app/controllers/admin/Category.php
  app/controllers/admin/Product.php
  app/views/client/products/list.php
Labels: fix

#71 refactor: admin side
  CoffeeShop.sql
  app/controllers/admin/Category.php
  app/controllers/admin/Product.php
  app/controllers/admin/User.php
  app/controllers/client/Account.php
  app/models/AccountModel.php
  app/views/admin/categories/add.php
  app/views/admin/categories/edit.php
  app/views/admin/components/deleteModal.php
  app/views/admin/components/restoreModal.php
  app/views/admin/products/add.php
  app/views/admin/products/edit.php
  app/views/admin/users/add.php
  app/views/admin/users/edit.php
  app/views/admin/users/info.php
  app/views/client/account/account.php
  app/views/client/account/changePassword.php
  app/views/client/account/formSignIn.php
  app/views/client/account/formSignUp.php
  configs/routes/admin/category.php
  configs/routes/admin/product.php
  configs/routes/admin/users.php
  core/Controller.php
  public/assets/images/default-customer-image.png
Labels: refactor

#72 feat: add manage order page
  app/controllers/admin/Order.php
  app/models/OrderModel.php
  app/views/admin/components/menu.php
  app/views/admin/orders/detail.php
  app/views/admin/orders/list.php
  app/views/admin/orders/ordersDeleted.php
  configs/constants/routes/admin/index.php
  configs/constants/routes/admin/orders.php
  configs/routes/admin/index.php
  configs/routes/admin/orders.php
Labels: feature

#73 28-11-2023, Version 2.14.9
  CoffeeShop.sql
  app/controllers/admin/Category.php
  app/controllers/admin/Order.php
  app/controllers/admin/Product.php
  app/controllers/admin/User.php
  app/controllers/client/Account.php
  app/models/AccountModel.php
  app/models/OrderModel.php
  app/views/admin/categories/add.php
  app/views/admin/categories/edit.php
  app/views/admin/components/deleteModal.php
  app/views/admin/components/menu.php
  app/views/admin/components/restoreModal.php
  app/views/admin/orders/detail.php
  app/views/admin/orders/list.php
  app/views/admin/orders/ordersDeleted.php
  app/views/admin/products/add.php
  app/views/admin/products/edit.php
  app/views/admin/users/add.php
  app/views/admin/users/edit.php
  app/views/admin/users/info.php
  app/views/client/account/account.php
  app/views/client/account/changePassword.php
  app/views/client/account/formSignIn.php
  app/views/client/account/formSignUp.php
  configs/constants/routes/admin/index.php
  configs/constants/routes/admin/orders.php
  configs/routes/admin/category.php
  configs/routes/admin/index.php
  configs/routes/admin/orders.php
  configs/routes/admin/product.php
  configs/routes/admin/users.php
  core/Controller.php
  public/assets/images/default-customer-image.png
Labels: release
