Repository linhpq0610/CoffeeShop, pull requests merged in 2023-12, with the labels that each got.

#80 chore: restructure folder
  app/controllers/admin/Product.php
  app/controllers/admin/User.php
  app/controllers/client/Account.php
  app/views/admin/dashboard.php
  app/views/admin/layouts/layout.php
  app/views/admin/orders/detail.php
  app/views/admin/orders/list.php
  app/views/admin/orders/ordersDeleted.php
  app/views/admin/products/add.php
  app/views/admin/products/edit.php
  app/views/admin/products/info.php
  app/views/admin/products/list.php
  app/views/admin/products/productsDeleted.php
  app/views/admin/statistics/comment.php
  app/views/admin/statistics/commentList.php
  app/views/admin/statistics/commentsDeletedInProduct.php
  app/views/admin/users/add.php
  app/views/admin/users/edit.php
  app/views/admin/users/info.php
  app/views/admin/users/list.php
  app/views/admin/users/usersDeleted.php
  app/views/client/account/account.php
  app/views/client/components/commentForm.php
  app/views/client/components/comments.php
  app/views/client/components/popularProducts.php
  app/views/client/components/relatedProducts.php
  app/views/client/contact/contact.php
  app/views/client/layouts/layout.php
  app/views/client/products/detail.php
  app/views/client/products/list.php
  configs/constants/directories.php
  configs/constants/urls.php
  core/Controller.php
  public/assets/css/admin/style.css
  public/assets/css/client/style.css
  public/assets/css/client/tiny-slider.css
  public/assets/images/contact.png
  public/assets/js/admin/chart-area-demo.js
  public/assets/js/admin/chart-bar-demo.js
  public/assets/js/admin/scripts.js
  public/assets/js/client/custom.js
  public/assets/js/client/tiny-slider.js
  public/assets/scss/style.scss
  public/plugins/bootstrap/bootstrap.bundle.min.js
  public/plugins/bootstrap/bootstrap.min.css
  uploads/products/arabica.png
  uploads/products/coffee-cup.png
  uploads/products/coffee-maker.png
  uploads/products/default-product-image.png
  uploads/products/kettle-coffee.png
  uploads/products/milk-coffee.png
  uploads/users/default-user-image.webp
  uploads/users/person-1.jpg
  uploads/users/person-1.png
  uploads/users/person_1.jpg
  uploads/users/person_2.jpg
  uploads/users/person_3.jpg
  uploads/users/person_4.jpg
Labels: chore

#82 feat: add order page client side
  CoffeeShop.sql
  app/controllers/client/Order.php
  app/errors/404.php
  app/errors/500.php
  app/errors/isNotAdmin.php
  app/errors/isNotSignedIn.php
  app/models/OrderModel.php
  app/views/client/cart/bills.php
  app/views/client/cart/cart.php
  app/views/client/cart/detailBill.php
  app/views/client/components/emptyCart.php
  app/views/client/components/header.php
  app/views/client/components/itemsInOrder.php
  configs/constants/routes/client/index.php
  configs/constants/routes/client/orders.php
  configs/routes/client/index.php
  configs/routes/client/orders.php
  core/Database.php
  public/assets/images/empty-cart.jpg
  public/assets/images/order-history.svg
Labels: feature

#86 refactor: client side
  app/controllers/client/Account.php
  app/controllers/client/Order.php
  app/models/HomeModel.php
  app/views/admin/layouts/layout.php
  app/views/client/cart/detailBill.php
  app/views/client/components/popularProducts.php
  app/views/client/layouts/layout.php
  public/plugins/froala-editor/froala_editor.pkgd.min.css
  public/plugins/froala-editor/froala_editor.pkgd.min.js
Labels: refactor

#87 chore: update Validator.js and Account controller
  app/controllers/client/Account.php
  features/Validator.js
Labels: chore

#88 docs: add guide
  README.md
  guide-install-libraries.png
  guide-install-source-code.png
Labels: documentation

#89 feat: update admin controllers
  app/controllers/admin/Category.php
  app/controllers/admin/Product.php
  app/controllers/admin/User.php
  app/views/admin/categories/add.php
  app/views/admin/categories/edit.php
  app/views/admin/products/add.php
  app/views/admin/products/edit.php
  app/views/admin/users/add.php
  app/views/admin/users/edit.php
  app/views/client/account/account.php
  app/views/client/account/changePassword.php
  app/views/client/account/createPasswordForm.php
  app/views/client/account/forgotPassword.php
  app/views/client/account/formSignIn.php
  app/views/client/account/formSignUp.php
  app/views/client/account/newPassword.php
  app/views/client/contact/contact.php
  public/plugins/validatejs/validate.min.js
Labels: feature

#90 fix: error appearance
  app/views/client/cart/bills.php
  app/views/client/cart/detailBill.php
  app/views/client/components/bills.php
  app/views/client/components/empty-cart.png
  app/views/client/components/emptyCart.php
  app/views/client/components/itemsInOrder.php
  app/views/client/components/noBill.php
  app/views/client/products/detail.php
  app/views/client/products/list.php
  public/assets/images/empty-cart.jpg
  public/assets/images/empty-cart.png
  public/assets/images/no-bill.png
  public/assets/images/shopping-cart-full-item.avif
Labels: fix

#92 feat: update web email
  app/controllers/client/Account.php
  configs/constants/php-mailer.php
Labels: feature

#93 feat: Thêm chức năng gửi form liên hệ
  app/controllers/client/Contact.php
  app/views/client/contact/contact.php
  configs/constants/php-mailer.php
  configs/constants/routes/client/index.php
  configs/routes/client/index.php
Labels: feature

#95 feat: validate comment form
  app/views/client/components/commentForm.php
  app/views/client/products/detail.php
Labels: feature

#96 feat: update send method in Mail.php
  app/errors/mailCanNotSend.php
  core/ErrorHandler.php
  core/Mail.php
Labels: feature

#97 feat: add change quantity in cart feature
  app/controllers/client/Order.php
  app/models/OrderModel.php
  app/views/client/components/itemsInOrder.php
  configs/constants/routes/client/orders.php
  configs/routes/client/orders.php
Labels: feature
